---
- name: Setup nginx configuration for project
  template:
    src: "team-project.conf.j2"
    dest: "/etc/nginx/sites-available/team-project.conf"

- name: Link configuration to sites-enabled
  file:
    src: '/etc/nginx/sites-available/team-project.conf'
    dest: '/etc/nginx/sites-enabled/team-project.conf'
    state: link

- name: Setup php user
  lineinfile:
    path: /etc/php/7.4/fpm/pool.d/www.conf
    regexp: '^user'
    line: 'user = vagrant'

- name: Setup php group
  lineinfile:
    path: /etc/php/7.4/fpm/pool.d/www.conf
    regexp: '^group'
    line: 'group = vagrant'

#- name: Composer Install
#  become: yes
#  become_user: vagrant
#  composer:
#    command: install
#    working_dir: '/var/www/web'
#    no_plugins: yes
#    no_scripts: yes

- name: Create database
  become: yes
  become_user: vagrant
  shell: 'php /var/www/web/bin/console doctrine:database:create'

- name: Create tables
  become: yes
  become_user: vagrant
  shell: 'php /var/www/web/bin/console doctrine:schema:update -f'

- name: Install assets
  become: yes
  become_user: vagrant
  shell: 'php /var/www/web/bin/console assets:install'

- name: Restart php
  shell: 'service php7.4-fpm restart'

- name: Restart nginx
  shell: 'service nginx restart'
