Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "teamProject"
  config.vm.box_check_update = true

  config.vm.network :private_network, ip: "10.0.0.200"
  config.vm.synced_folder "..", "/var/www"

  config.ssh.forward_agent = true
    config.vm.provider :virtualbox do |p|
      p.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      p.customize ["modifyvm", :id, "--memory", 2048]
      p.customize ["modifyvm", :id, "--name", "teamProject"]
      p.customize ["modifyvm", :id, "--cpuexecutioncap", "80"]
      p.cpus = 1
    end
    config.vm.provision :ansible do |a|
      a.playbook = "provision.yaml"
      a.inventory_path = "./hosts"
      a.limit = "teamProject"
    end
end
