admin-default-index:
  path: /admin/
  controller: App\Controller\Admin\DefaultController::index

users:
  resource: 'admin/users-controller.yaml'
  prefix: /admin/users

articles:
  resource: 'admin/articles-controller.yaml'
  prefix: /admin/articles